# Foundation of Statistics
Branch of Mathematics that deals with collecting, organizing, analyzing, interpreting and presenting data. Using different statistical tools( mean, median, mode, percentile, etc....), we try to learn information from the data, and turn the raw data into meaningful and actionable insights.

## Statistics

Statistics is the branch of mathematics that deals with collecting, organizing, analyzing, interpreting, and presenting data.

### It has two main branches
- Descriptive Statistics
- Inferential Statistics

</br>

---

# Why is Statistics Important

Without stats, data is just a collection of numbers with no context.
Stats provides us with tools which we can use to gain information from the data like, trend, test assumptions, make data-driven decisions.
- Summarize data
- Find patterns
- Extract insights

## Statistics In Daily Life

1) Finance and Insurance
2) Education
3) Business
4) Stock Market
5) Census
6) Sports
7) Sales and Marketing
8) Weather Forecasting
9) Web applications
10) Economy
11) Healthcare

## Stats in Data Analytics
Data Analysts use stats to dissect historical data/performance. By using stats tools, and calculation average, growth rates, percentage, etc.... they basically summarize the past data and explain what happened and why it happened.

### Backbone of any AIML model
- Statistics 
- Mathematics
- Linear Algebra

</br>

### Used in
- Algorithms: All the ML models are directly using statistical patterns.
- Model Evaluation Metrics: Metrics (measures used to evaluate the performance of a Ml model), RMSE, MSE, R^2 score
- Feature selection
- Feature creation/engineering
- Prediction and Forecasting
- Understand the behaviors of customers
- Outlier detection

</br>

---


# Types of Statistics

### 1) Descriptive Statistics

Used to describe the data, summarize the data .

Its describes the data using tools like - mean, median, mode, variance, standard div,etc.....

</br>

### 2) Inferential Statistics

We use a sample from the data(population) and we try to infer something about the population using the sample. We try to make predictions, decisions about the entire population from the sample.

Tools --> Hypothesis testing like 
- Z test
- T test
- Anova
- Chi sq

</br>

---

# Basic statistical Terminologies

### Population
- The entire data --> The complete dataset
- Example --> all the registered voters in India

### Sample
- Subset of data taken from the population
- Example --> 5000 voters from all the voters list

</br>

### Census vs Sampling

- Census- data collection from every member of the population.

- Sampling- Data collection from a selected sample of people

</br>

---


# Types of Data

### Qualitative Data (Categorical)

- Data that describes qualities of an entity.
- They can't be measured on a numerical sale.
- But you can have numbers as categories( 0, 1 etc)
- Ex: gender, species, age group , department, etc...

</br>

### Quantitative Data (Numerical)

- Data that represent numbers or measurable quantities. 
- Ex: age , salary , sales, profit, etc...

</br>

1. Discrete data
- Numerical values that the countable. Generally there are no fraction or decimal numbers.
- Ex: Number of children, numbers bank account transfer, website clicks per days, number of sales, number of butterflies in a area

</br>

2. Continuous data
- Numerical values that are measurable.
- Ex: Sales amount, bank account balance, Salary, age, height, Avg Wing Length of the butterflies

</br>

---

# Descriptive Statistics

## 1) Measure of Central Tendency

- Finding the center of the data.
- It provide a single value that can identify the central core or center point of the data.
- One single value representing the entire data in some way.
- Ex: Mean, Median , Mode

</br>

| Measure | Meaning             |
| ------- | ------------------- |
| Mean    | Average value       |
| Median  | Middle value        |
| Mode    | Most frequent value |

</br>

---

### Mean / Average
- The sum of all the points , divided by the total number of points.
- Ex: Average marks of class, Average sales of April Month, Average weight of Cattle, Average salary, Milage.

<img src="./images/Mean.png" width="380">

<img src="./images/MeanExample.png" width="270">

- Missing value filling
- Feature Engineering
- Data summarization

In [2]:
data = [ 7, 2, 15, 19, 50, 11, 22]
n = len(data)
total_sum = sum(data)

m = total_sum/n

print("Mean = ", m)

Mean =  18.0


In [3]:
import numpy as np

arr = np.random.randint(0, 100, size = 100)

# Average of the arr elements
print("Mean = ", np.mean(arr))

Mean =  49.32


In [4]:
import statistics as stats

print("mean = ", stats.mean(data))

mean =  18


---

### Median
- The middle value when the data is sorted in any order( ascending or descending).

<img src="./images/MedianOdd.png" width="280">

<img src="./images/MedianEven.png" width="350">

<img src="./images/MedianOddEx.png" width="290">

<img src="./images/MedianEvenEx.png" width="230">

In [6]:
# Odd Number of elements

data1 = np.random.randint(0, 100, size=9)
print(data1)

[98 83  7 19 37 83 33 36 20]


In [7]:
data1.sort()
print(data1)

[ 7 19 20 33 36 37 83 83 98]


In [9]:
# [ 7 19 20 33 36 37 83 83 98]
#   0  1  2  3  4  5  6  7  8
#               |

n = 9   # 9 elements

pos = n // 2   # 9//2 -> 4
print(pos)

print(data1[pos]) # Median

4
36


In [10]:
# Even number of elements

data2 = np.random.randint(0, 100, size=10)
print(data2)

[35 70 96 63 97 84 34 20 97 32]


In [11]:
data2.sort()
data2

array([20, 32, 34, 35, 63, 70, 84, 96, 97, 97], dtype=int32)

In [12]:
# [20, 32, 34, 35, 63, 70, 84, 96, 97, 97]
#  0    1  2   3   4    5  6   7   8    9
#                  |    |
n = 10

pos1 = 10 // 2          # 5
pos2 = (10 // 2) - 1    # 5-1 =4

# Average of data[pos1] and data[pos2]

m = (data2[pos1] + data2[pos2])/2

print(m)

66.5


In [13]:
print(np.median(data1))
print(np.median(data2))

36.0
66.5


In [14]:
print(stats.median(data1))
print(stats.median(data2))

36
66.5


---

### Mode
- The element having the most frequency or counts

<img src="./images/Mode.png" width="280">

### Types of Mode

1. Unimodal

```
2, 3, 3, 4, 5
3 appears most frequently
Mode = 3
```

2. Bimodal

```
1, 2, 2, 3, 3, 4
2 appears 2 times
3 appears 2 times
Mode = 2, 3
```

3. Multimodal

```
1, 1, 2, 2, 3, 3, 4
1 repeats 2 times
2 repeats 2 times
3 repeats 2 times
Modes = 1, 2, 3
```

- Which gender is most prominent
- Which department have the most people
- Which product is the most popular
- What is the most common blood group
- Which mobile brand is purchased the most
- Which IPL team has won the most
- Most common disease

In [ ]:
genders = ["M","F","M","F","F","M","F","F","F","F","M"]

print(stats.mode(genders))  # Unimode

F


In [17]:
colors=["Red","Blue","Blue","Blue","Green","Red","Red"]
# Red- 3
# Blue- 3
# green- 1

print(stats.multimode(colors))

['Red', 'Blue']


---

## 2) Measure of Spread or Dispersion