# Linear Algebra Handson

- Matrix
- Matrix Operations
- Transpose of Matrix
- Determinant of Matrix
- Inverse of Matrix
- Eigen values and vectors

<https://colab.research.google.com/drive/1wex__RUYRDBdmBdhiyaRH14AgMHuoxo6?usp=sharing#scrollTo=iFzBQ4hA-Spq>

---

### 1. Create a 3*3 random value matrix (3 rows and 3 columns)

In [29]:
import numpy as np

In [30]:
matrix = np.random.randint(0,101,(3,3))
matrix

array([[63, 57, 39],
       [70, 60, 37],
       [96, 68, 37]], dtype=int32)

---

### 2. matrix operations

- add 50 to the matrix
- subtract 20 from matrix
- mulply matrix by 3
- devide matrix by 4

In [31]:
#addition

result = matrix + 50
result

array([[113, 107,  89],
       [120, 110,  87],
       [146, 118,  87]], dtype=int32)

In [32]:
#subtraction
result = matrix - 20
result

array([[43, 37, 19],
       [50, 40, 17],
       [76, 48, 17]], dtype=int32)

In [33]:
result = matrix * 3
result

array([[189, 171, 117],
       [210, 180, 111],
       [288, 204, 111]], dtype=int32)

In [34]:
result = matrix / 4
result

array([[15.75, 14.25,  9.75],
       [17.5 , 15.  ,  9.25],
       [24.  , 17.  ,  9.25]])

---

### 3. create two matrix of your choice and perform all the arithmetic operations on the metrices

In [35]:
A = np.array([[4, 7, 2],
              [3, 6, 1],
              [8, 5, 9]])

B = np.array([[1, 3, 5],
              [2, 4, 6],
              [7, 8, 9]])

In [36]:
# Element-wise Addition
print(A + B)

[[ 5 10  7]
 [ 5 10  7]
 [15 13 18]]


In [37]:
# Element-wise Subtraction
print(A - B)

[[ 3  4 -3]
 [ 1  2 -5]
 [ 1 -3  0]]


In [38]:
# Element-wise Multiplication
print(A * B)

[[ 4 21 10]
 [ 6 24  6]
 [56 40 81]]


In [39]:
# Element-wise Division
print(A / B)

[[4.         2.33333333 0.4       ]
 [1.5        1.5        0.16666667]
 [1.14285714 0.625      1.        ]]


In [40]:
# Matrix Multiplication (dot product)
print(A @ B)

[[ 32  56  80]
 [ 22  41  60]
 [ 81 116 151]]


---

### 4. Perform dot product between two matrics of (2*2)

In [41]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [42]:
dot_product = np.dot(A, B)
print(dot_product)

[[19 22]
 [43 50]]


In [43]:
print(A @ B)

[[19 22]
 [43 50]]


In [44]:
print(A.dot(B))

[[19 22]
 [43 50]]


---

### 5. Take a 3*3 matrix and transpose it

In [45]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [ ]:
transposed = matrix.T

# make rows into column

print(transposed)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


---

In [47]:
A = np.random.randint(1, 10, (4, 4))
B = np.random.randint(1, 10, (3, 4))

In [48]:
np.dot(A, B)

ValueError: shapes (4,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

When number of column of the 1st matrix is not equal to number of rows in the 2nd matrix

then dot product is not possible

---

### 6. take (3*3) matrix and prove this property
### Property 1: Transpose of a Transposed matrix is the original Matrix

In [58]:
A = np.array([[3, 7, 2],
              [8, 1, 5],
              [4, 6, 9]])

In [59]:
# First transpose
B = A.T

In [60]:
print(B)

[[3 8 4]
 [7 1 6]
 [2 5 9]]


In [61]:
# Second transpose
C = A.T.T

In [62]:
print(C)

[[3 7 2]
 [8 1 5]
 [4 6 9]]


In [64]:
print("\nIs (Aᵀ)ᵀ == A?", np.array_equal(C, A))


Is (Aᵀ)ᵀ == A? True


---

### 7. take (3*3) matrix and prove this property
### Property 2: Additive Property , (A+B).T = A.T + B.T

In [65]:
A = np.array([[1, 4, 7],
              [2, 5, 8],
              [3, 6, 9]])

B = np.array([[9, 3, 6],
              [8, 2, 5],
              [7, 1, 4]])

In [66]:
# LHS: (A + B).T
LHS = (A + B).T

print(LHS)

[[10 10 10]
 [ 7  7  7]
 [13 13 13]]


In [67]:
# RHS: A.T + B.T
RHS = A.T + B.T

print(RHS)

[[10 10 10]
 [ 7  7  7]
 [13 13 13]]


In [69]:
print("\n(A+B).T == A.T + B.T :", np.array_equal(LHS, RHS))


(A+B).T == A.T + B.T : True


---

### 8. take (3*3) matrix and prove this property
### Property 3: (Mutliplicative Property), (AxB).T = B.T x A.T

In [71]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [72]:
L = (A @ B).T

print(LHS)

[[10 10 10]
 [ 7  7  7]
 [13 13 13]]


In [73]:
R = B.T @ A.T

print(RHS)

[[10 10 10]
 [ 7  7  7]
 [13 13 13]]


In [ ]:
print("\nIs (AxB).T == B.T x A.T ?", np.array_equal(L, R))


Is (A×B).T == B.T × A.T ? True


---

### Determinant

### It tells us if a matrix has an inverse
### If a matrix has unique sol or not

<img src="Determinant-of-Square-Matrix.png" width="480">

In [78]:
x = np.array([[1,2],[3,4]]) # 4-6 = -2
x

array([[1, 2],
       [3, 4]])

In [79]:
print(np.linalg.det(x))

-2.0000000000000004
