# HandsOn

In [1]:
import numpy as np

### Q1. Create a numpy array with shape 2x5 that has all the elements as zeros.

In [34]:
arr = np.zeros((2, 5), dtype = 'int')
arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

### Q2. Create a numpy array that has the shape 3x5 and all the elements are 5.

In [10]:
arr = np.full((3, 5), 5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [11]:
arr = np.full((3, 5), np.random.randint(5, 6))
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [12]:
arr = np.repeat(5, 15).reshape(3,5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [14]:
arr = np.tile(5, (3, 5))
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

### Create a numpy array with random integers in the range 0-100, and the sample size should be 25.

In [18]:
arr = np.random.choice(range(0, 101),  size = 25)
arr

array([32, 52, 26, 68, 11, 53, 73, 55, 81,  3, 41, 84, 17, 94, 91,  0, 23,
       18,  6, 58, 70, 18, 49, 31, 85])

In [20]:
arr = np.random.randint(0,101,25)
arr

array([ 76,  96,  63,   2,  23,  19,  57,  53,  35,  20,  85, 100,  35,
        78,  12,  15,  83,  39,  70,  85,  22,  82,  85,  48,  95],
      dtype=int32)

### Create a numpy array with a shape 3x3 that has all elements as 1

In [21]:
ones = np.ones((3, 3), dtype = 'int')
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### Create a random array, with the range 0-1000, with a size 50 and 
### Perform the following operations on the same.
- a. Print the first ten elements of the array.
- b. Print the last ten elements of the array
- c. Print the elements from the indexes 10-25
- d. Print the element at the index 22
- e. Print the array using negative indexing.
- f. Print the last ten elements of the array, using negative indexing.


In [38]:
arr = np.random.choice(range(0, 1001),  size = 50)
arr

array([252, 294, 658, 912, 595, 620,  31, 798, 676, 896, 731, 486, 510,
       744, 562, 354, 173, 258, 368, 158, 837,  80, 848, 859, 917, 157,
       879, 608, 678, 440, 155,  71,  27, 149,  56, 299, 615, 460, 254,
       165, 161, 643, 267, 834, 689, 746, 857, 801, 866,  41])

In [39]:
arr[0:10]
arr[:10]

array([252, 294, 658, 912, 595, 620,  31, 798, 676, 896])

In [42]:
arr[40:50]
arr[40:]

array([161, 643, 267, 834, 689, 746, 857, 801, 866,  41])

In [43]:
arr[10:26]

array([731, 486, 510, 744, 562, 354, 173, 258, 368, 158, 837,  80, 848,
       859, 917, 157])

In [44]:
arr[22]

np.int64(848)

In [45]:
arr[-50:]

array([252, 294, 658, 912, 595, 620,  31, 798, 676, 896, 731, 486, 510,
       744, 562, 354, 173, 258, 368, 158, 837,  80, 848, 859, 917, 157,
       879, 608, 678, 440, 155,  71,  27, 149,  56, 299, 615, 460, 254,
       165, 161, 643, 267, 834, 689, 746, 857, 801, 866,  41])

In [46]:
arr[-10:]

array([161, 643, 267, 834, 689, 746, 857, 801, 866,  41])

### Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
- a. Insert the element 6 at the end of the array.
- b. Insert the element 10 at the beginning of the array.
- c. Insert the element 30, before 4.
- d. Update the element 5 as 50.
- e. Delete the element 50 in the updated array.
- f. Create a function to search for the element 30.
- g. Sort the array in ascending order.

In [61]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [62]:
arr = np.append(arr, 6)
arr

array([1, 2, 3, 4, 5, 6])

In [63]:
arr = np.insert(arr, 0, 10)
arr

array([10,  1,  2,  3,  4,  5,  6])

In [64]:
arr = np.insert(arr, 4, 30)
arr

array([10,  1,  2,  3, 30,  4,  5,  6])

In [69]:
arr[arr == 5] = 50
arr

array([10,  1,  2,  3, 30,  4, 50,  6])

In [71]:
arr = np.delete(arr, -2)
arr

array([10,  1,  2,  3, 30,  4,  6])

In [73]:
def search(arr, element):
    index = np.where(arr == element)[0]
    if index.size > 0:
        print(f"\nElement {element} found at index: {index[0]}")
    else:
        print(f"\nElement {element} not found in the array")

search(arr, 30)


Element 30 found at index: 4


In [74]:
arr = np.sort(arr)
arr

array([ 1,  2,  3,  4,  6, 10, 30])

### marks = np.array([45, 67, 89, 34, 90, 56])
- These are the marks of the students

- find highest, lowest, total and average marks
- add 5 grace marks to the marks of all students
- replace for all students who have got marks below 40 as Fail
- filter out students who have got marks more than 60.

In [75]:
marks = np.array([45, 67, 89, 34, 90, 56])
marks

array([45, 67, 89, 34, 90, 56])

In [76]:
print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))
print(np.mean(marks))

90
34
381
63.5


In [77]:
marks = marks + 5
marks

array([50, 72, 94, 39, 95, 61])

In [78]:
result = marks.astype(object)
result[result < 40] = "Fail"
result

array([50, 72, 94, 'Fail', 95, 61], dtype=object)

In [79]:
filtered = marks[marks > 60]
filtered

array([72, 94, 95, 61])