# NUMPY

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
!pip install numpy

In [1]:
import numpy as np

Drawbacks of List:

- lists are comparatively slower
- data is being stored at different positions
- we cannot perform arithmetic operation on them
- lists cannot have multidimensional data

---

Considering all these drawbacks numpy arrays are very good choice for performing mathematical operations

---

## Numpy arrays

1. Numpy arrays are very similar to the list
2. They are faster
3. The values are stored at contigous memory locations
4. We are able to perform mathematical operations
5. Homogenous

## Creating numpy arrays

In [5]:
arr1 = np.array([1, 2, 3])

print(arr1)

[1 2 3]


In [6]:
type(arr1)

numpy.ndarray

In [7]:
type(arr1[1])

numpy.int64

In [9]:
arr2 = np.array([1, 'x', 3])

type(arr2[1])

numpy.str_

In [11]:
print(arr1.dtype)
print(arr2.dtype)

int64
<U21


In [14]:
arr3 = np.array([1, True])
print(arr3)
print(arr3.dtype)

[1 1]
int64


In [16]:
arr4 = np.array([1, True, 1.5])
print(arr4)
print(arr4.dtype)

[1.  1.  1.5]
float64


In [17]:
arr5 = np.array([1, True, 1.5, 'abc'])
print(arr5)
print(arr5.dtype)

['1' 'True' '1.5' 'abc']
<U32


### Flow of convertion
bool < int < float < str

## Dimention

in numpy dimention is basically column

### Zero dimensional array

In [18]:
zero_dim = np.array(24)
print(zero_dim)

24


In [19]:
zero_dim.ndim

0

In [ ]:
# ndim -- it tells me about the dimension of the array

### One dimensional array

In [20]:
one_dim = np.array([12,24,36])
print(one_dim)

[12 24 36]


In [21]:
one_dim.ndim

1

In [22]:
# array length in numpy

one_dim.shape

(3,)

### Two dimensional array

In [23]:
two_dim = np.array([[1,2,3],[4,5,6]])
print(two_dim)

[[1 2 3]
 [4 5 6]]


In [24]:
two_dim.ndim

2

In [26]:
two_dim.shape

# as per the shape

# 1st value -- number of 1d arrays -- rows
# 2nd value -- values present inside 1d array -- number of columns

(2, 3)

### Three dimensional array

In [27]:
three_dim = np.array([[[1,2], [3,4]], [[4,5], [6,7]]])
print(three_dim)

[[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


In [31]:
three_dim.ndim

3

In [32]:
three_dim.shape

(2, 2, 2)

In [ ]:
[ [  [ ], [ ]  ],    [  [ ], [ ]  ] ]

In [ ]:
# 1st value -- no of 2d arrays
# 2nd value -- no of row
# 3rd value -- no of columns

In [33]:
d = np.array([[[1,2],[4,5],[6,7]], [[1,2],[4,5],[6,7]], [[1,2],[4,5],[6,7]]])
d

array([[[1, 2],
        [4, 5],
        [6, 7]],

       [[1, 2],
        [4, 5],
        [6, 7]],

       [[1, 2],
        [4, 5],
        [6, 7]]])

In [34]:
d.shape

(3, 3, 2)

In [35]:
ar1 = np.array([[1,24,5,6,7],[44,22,11,22,33],[1,21,22,42,43]])
ar1

array([[ 1, 24,  5,  6,  7],
       [44, 22, 11, 22, 33],
       [ 1, 21, 22, 42, 43]])

In [36]:
ar1.shape

(3, 5)

## Accessing the elements from the array

- indexing -- access one single element
- slicing -- when we want a part of our data can be single also multiple

In [37]:
a = np.array([33,34,35,29])
a

array([33, 34, 35, 29])

In [38]:
# access the element 35
print(a[2])

35


In [39]:
b = np.array([[1,2,3],[23,41,45]])
b

array([[ 1,  2,  3],
       [23, 41, 45]])

In [40]:
b[0,0]

np.int64(1)

In [2]:
# Reshape
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.shape

(12,)

In [3]:
arr.size

12

In [8]:
# length = 12 = 2x6
arr_reshape = arr.reshape(2, 6)
arr_reshape

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [9]:
# length = 12 = 6x2
arr_reshape = arr.reshape(6, 2)
arr_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
# in rehape 1st parameter is row, 2nd param is column

In [11]:
# length = 12 = 3x2x2
arr_reshape = arr.reshape(3, 2, 2)
arr_reshape

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [ ]:
# single value -- number of elements
# two values -- row and columns
# three values -- number of 2d arrays, rows and columns
# four values --number of 3d arrays, no of 2d arrays, rows and columns

## slice

In [18]:
# 1D slicing
a [start : end + 1]
a [10, 12, 13, 14]
a [0 : 3]
a [ : 3]

In [15]:
a = np.array([10, 12, 13, 14])

In [16]:
a [0 : 3]

array([10, 12, 13])

In [22]:
a [ : 3] # is start value is start index of array, then we can leave it

array([10, 12, 13])

In [ ]:
### 2D slicing

In [27]:
b = np.array([[1,2,3], [4,5,6]])

In [28]:
b [0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [32]:
b [0:2, 1:2]

array([[2],
       [5]])

In [33]:
# skip 1 value
b [ : , : : 2]

array([[1, 3],
       [4, 6]])