# Linear Algebra

<https://jalammar.github.io/visual-numpy/>

<https://colab.research.google.com/drive/1_mLRSpd51jPNhtlWZmuXXjnHoIcjSBlv#scrollTo=FBOTxwezgC9n>

In [2]:
import numpy as np

In [3]:
vector = np.arange(5)

In [4]:
vector * 10

array([ 0, 10, 20, 30, 40])

In [5]:
np.arange(24).reshape(6, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [6]:
import pandas as pd
tips = pd.read_csv('tips.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'tips.csv'

In [ ]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [ ]:
tips.values # .values will convert a dataframe into a numpy array

array([[16.99, 1.01, 'Female', ..., 'Sun', 'Dinner', 2],
       [10.34, 1.66, 'Male', ..., 'Sun', 'Dinner', 3],
       [21.01, 3.5, 'Male', ..., 'Sun', 'Dinner', 3],
       ...,
       [22.67, 2.0, 'Male', ..., 'Sat', 'Dinner', 2],
       [17.82, 1.75, 'Male', ..., 'Sat', 'Dinner', 2],
       [18.78, 3.0, 'Female', ..., 'Thur', 'Dinner', 2]], dtype=object)

In [ ]:
mat1 = np.random.randint(10, 51, size = (3,3))
mat2 = np.random.randint(50, 100, size = (3,3))

In [ ]:
mat1

array([[32, 48, 46],
       [33, 15, 22],
       [47, 21, 20]])

In [ ]:
mat2

array([[72, 65, 61],
       [88, 77, 79],
       [78, 70, 81]])

In [ ]:
#addition of matrices
mat1 + mat2 #np.add(mat1, mat2)

array([[104, 113, 107],
       [121,  92, 101],
       [125,  91, 101]])

In [ ]:
mat1 + 10

array([[42, 58, 56],
       [43, 25, 32],
       [57, 31, 30]])

In [ ]:
#subtraction of matrices
mat1 - mat2   #np.subtract(mat1, mat2)

array([[-40, -17, -15],
       [-55, -62, -57],
       [-31, -49, -61]])

In [ ]:
mat2 - mat1

array([[40, 17, 15],
       [55, 62, 57],
       [31, 49, 61]])

In [ ]:
#division of matrices
mat1 / 10

array([[3.2, 4.8, 4.6],
       [3.3, 1.5, 2.2],
       [4.7, 2.1, 2. ]])

In [ ]:
mat1 / mat2  #np.divide(mat1, mat2)

array([[0.44444444, 0.73846154, 0.75409836],
       [0.375     , 0.19480519, 0.27848101],
       [0.6025641 , 0.3       , 0.24691358]])

In [ ]:
#element-wise multiplication or Hadamard product
mat1 * mat2   #np.multiply(mat1, mat2)

array([[2304, 3120, 2806],
       [2904, 1155, 1738],
       [3666, 1470, 1620]])

In [ ]:
#actual matrix multiplication : Dot product
mat1 @ mat2 #np.dot(mat1, mat2)

array([[10116,  8996,  9470],
       [ 5412,  4840,  4980],
       [ 6792,  6072,  6146]])

In [ ]:
mat1

array([[32, 48, 46],
       [33, 15, 22],
       [47, 21, 20]])

In [ ]:
#transpose of a matrix
mat1.T

array([[32, 33, 47],
       [48, 15, 21],
       [46, 22, 20]])

In [ ]:
#matrix rank : helps us to identify duplicate or redundant data
np.linalg.matrix_rank(mat1)

np.int64(3)

In [ ]:
#determinant of a matrix : whether a matrix is singular or not
np.linalg.det(mat1)

np.float64(15204.000000000015)

In [ ]:
mat3 = np.arange(9).reshape(3,3)

In [ ]:
mat3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
np.linalg.det(mat3)

np.float64(0.0)

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
#inverse of a matrix
mat1_inv = np.linalg.inv(mat1)

In [ ]:
mat1_inv

array([[-0.0132613 ,  0.00049116,  0.02996071],
       [ 0.03061559, -0.1245907 ,  0.06663392],
       [-0.00098232,  0.12966601, -0.09037328]])

In [ ]:
np.round((mat1_inv @ mat1), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [ ]:
np.linalg.inv(mat3)

LinAlgError: Singular matrix

In [ ]:
matrix = np.array([[3, -2],
                   [1, 0]])

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Original Matrix: ")
print(matrix)
print('\nEigenvalues: ')
print(eigenvalues)
print('\nEigenvectors: ')
print(eigenvectors)

Original Matrix: 
[[ 3 -2]
 [ 1  0]]

Eigenvalues: 
[2. 1.]

Eigenvectors: 
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [ ]:
np.dot(matrix, [0.89442719, 0.4472136])

array([1.78885437, 0.89442719])

In [ ]:
np.array([0.89442719, 0.4472136]) * 2

array([1.78885438, 0.8944272 ])